[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  # Pin to exactly the Node version Netlify can install
  NODE_VERSION = "18.20.8"

[[plugins]]
  package = "@netlify/plugin-nextjs"
